-- select role based on which user want to perform operation with specific role
-- so before running ant sql query, set up your context 

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

-- create database under compute_wh warehouse
CREATE OR REPLACE DATABASE MYDB;

CREATE OR REPLACE SCHEMA MYDB.MYSCHEMA;
--SYNTEX OF DROP SCHEMA : (DROP SCHEMA MYSCHEMA)


/*-----------------------------------------------------------
    FOUR TYPE OF THE TABLE
-----------------------------------------------------------*/

--CREATE PERMANENT TABLE
CREATE OR REPLACE TABLE MYDB.MYSCHEMA.PERMANENT_TABLE
(
    ID INT,
    NAME STRING
);
-- ALLOW 0 TO 90 DAYS
ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 10;



--CREATE TRANSIENT TABLE
CREATE OR REPLACE TRANSIENT TABLE MYDB.MYSCHEMA.TRANSIENT_TABLE
(
    ID INT,
    NAME STRING
);
-- ALLOW 0 TO 1 DAYS
ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 0;



--CREATE TEMPORARY TABLE
CREATE OR REPLACE TEMPORARY TABLE MYDB.MYSCHEMA.TEMPORARY_TABLE
(
    ID INT,
    NAME STRING
);
-- ALLOW 0 TO 1 DAYS 
ALTER TABLE TEMPORARY_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 10; --(GIVE ERROR)


-- DISPLAY ALL TABLES
SHOW TABLES;







