USE SCHEMA MYDB.MYSCHEMA;

// HERE WE ARE USE THE JSON FORMAT TO GENERATE EVENT
// FOR THAT USE VARIANT DATATYPE FOR THE UNSTRUCTURED DATA

//CREATE AN EMPLOYEE TABLE FOR THE CONTINUES DATA 
CREATE OR REPLACE TABLE EVENT(
    EVENT VARIANT
);


CREATE OR REPLACE STORAGE INTEGRATIONS S3_SNOWPIPE_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'ROLE_LINK'
    STORAGE_ALLOWED_LOCATIONS = ('BUCKET_LINK');

// DESCRIBE THE STORAGE INTEGRTION
// UPDATE THE VALUE(EXTERNAL_ID) IN AWS FRO THIS MAKE TRUST RELATIONSHIP BETWEEN THE S3 AND SNOWFLAKE 
DESC INTEGRATION S3_SNOWPIPE_INT

// CREATE JSON FILE FORMAT 
CREATE OR REPLACE FILE FORMAT MY_JSON_FORMAT
TYPE = 'JSON'


//CREATE AN EXTERNAL S3 STAGE
CREATE OR REPLACE STAGE MY_S3_SNOWPIPE_STAGE
    STORAGE_INTERGATION = S3_SNOWPIPE_INT
    URL = 'BUCKET_LINK'
    FILE_FORMAT = MY_JSON_FORMAT


//ACCESS THE EXTERNAL STAGE
LIST @MY_S3_SNOWPIPE_STAGE  

//CREATE A SNOWPIPE TO LOAD EVENT DATA FROM S3
CREATE OR REPLACE PIPE S3_PIPE
AUTO_INGEST = TRUE AS 
    COPY INTO EVENT
    FROM @MY_S3_SNOWPIPE_STAGE
    FILE_FORMAT = (FORMAT_NAME = MY_JSON_FORMAT)

//DISPLAY THE STATUS OF THE PIPE
// S3 NOTIFICATION COMING THROUGH THE SQS QUEUE 
SELECT SYSTEM$PIPE_STATUS('S3_PIPE')

//GET THE NOTIFICATION CHANNEL
SHOW PIPES;

//SELECT DATA FROM THE TABLE 
SELECT * FROM EVENT;