
USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE S3_USER (
ID INTEGER,
NAME VARCHAR(50),
LOCATION VARCHAR(50),
EMAIL VARCHAR(50)
)


// CREATE AN STORAGE INTEGRATION S3 AND IAM ROLE 
// MAKE CONNECTION BETWEEN THE SE AND SNOWFLAKE

CREATE OR REPLACE STORAGE INTEGRATIONS S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'ROLE_LINK'
    STORAGE_ALLOWED_LOCATIONS = ('BUCKET_LINK');

// DESCRIBE THE STORAGE INTEGRTION
// UPDATE THE VALUE(EXTERNAL_ID) IN AWS FRO THIS MAKE TRUST ISSUE BETWEEN THE S3 AND SNOWFLAKE 
DESC INTEGRATION S3_INT

// CREATE FILE FORMAT 
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1

//CREATE AN EXTERNAL S3 STAGE
CREATE OR REPLACE STAGE MY_S3_STAGE
    STORAGE_INTERGATION = S3_INT
    URL = 'BUCKET_LINK'
    FILE_FORMAT = MY_CSV_FORMAT


//ACCESS THE EXTERNAL STAGE
LIST @MY_S3_STAGE

//LOAD DATA FROM THE S3 BUCKET TO S3_USER TABLE
COPY INTO S3_USER
FROM @MY_S3_STAGE
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)

SELECT * FROM S3_USER
