/*
    ~named object that stores information to parse file during load/unload
    ~create file format object as part of the stage, or specify within the copy command
*/

list @-;

USE WAREHOUSE COMPUTE_WH;
USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE STUDENT(
    ID INTEGER,
    NAME STRING,
    AGE INTEGER,
    MARKS INTEGER
)

CREATE OR REPLACE STAGE STUDENT_STAGE;

LIST @STUDENT_STAGE;

// CREATE CSV FILE FORMAT 
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1;


COPY INTO STUDENT 
FROM @STUDENT_STAGE 
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT * FROM STUDENT ;

/*-----------------FOR LOAD JSON DATA-------------*/

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON'

// DISPLAY ALL FILE FORMAT OBJECT 
SHOW FILE FORMATS;
