/*
    NAMED STORAGE LOCATION IN SNOWFLAKE WHERE YOU CAN TEMPORARILY LOAD OR UNLOAD DATA FILES 
    BEFORE TRANSFERING THEM TO SNOWFLAKE TABLE.

    1)INTERNAL STAGE: STORED INTERNALLY IN SNOWFLAKE
    2)EXTERNAL STAGE: STORED IN EXTERNAL LOCATION LIKE S3 BUCKET, ADLF

    CREATE STAGE OBJECT TO MANAGE INGESTION WORKLOAD
*/

/* TYPES OF STAGES   :  1)TABLE 2)USER STAGE   3) NAMED STAGE

    1)file needs to be accessable to MULTIPLE users and need to be copied into a SINGLE table 
      in that particular usecase will use TABLE stage.

    2)files will be only accessed by a SINGLE user but to be copied into a MULTIPLE table 
   
    3)NAMED STAGE can be accessed by MULTIPLE authorized users and load data into several tables
        (internal and external stage)
*/ 

USE SCHEMA MYDB.MYSCHEMA;

--CREATE AN CUSTOMER TABLE

CREATE OR REPLACE TABLE CUSTOMER (
    ID INTEGER,
    NAME STRING,
    AGE INTEGER,
    STATE VARCHAR(50)
);

--NOTE-- WHEN TABLE IS CREATED THEN SF AUTOMATICALLY CREATE TABLE STAGE 
-- ACCESS THE TABLE STAGE
LIST @%CUSTOMER;

--NOTE-- WHEN USER IS CREATED THEN SF AUTOMATICALLY CREATE USER STAGE 
-- ACCESS THE USER STAGE
LIST @-;

-- CREATE A NAMED STAGE
CREATE OR REPLACE STAGE CUSTOMER_STAGE;

//ACCESS THE NAME OF INTERNAL STAGE
LIST @CUSTOMER_STAGE ;

// LOAD DATA TO CUSTOMER TABLE
COPY INTO CUSTOMER 
FROM @CUSTOMER_STAGE
FILE_FORMAT = (TYPE ='CSV' SKIP_HEADER = 1);

//DISPLAY CUSTOMER TABLE
SELECT * FROM CUSTOMER;
