/*======WITHOUT TASK ======*/

-- CREATE SOURCE TABLE AND INSERT SOME DATA
CREATE OR REPLACE TABLE SOURCE_TABLE(
    ID INTEGER,
    NAME VARCHAR,
    CREATED_DATE DATE
);

INSERT INTO SOURCE_TABLE VALUES 
(1,'CHAOS','2019-11-23'),
(2,'GENION','2024-07-04')

SELECT * FROM SOURCE_TABLE;


-- CREATE TARGET TABLE AND INSERT SOME DATA

CREATE OR REPLACE TABLE TARGET_TABLE(
    ID INTEGER,
    NAME VARCHAR,
    CREATED_DATE DATE,
    CREATED_DAY VARCHAR,
    CREATED_MONTH VARCHAR,
    CREATED_YEAR VARCHAR
);

INSERT INTO TARGET_TABLE 
SELECT 
    S.ID,
    S.NAME,
    S.CREATED_DATE,
    DAY(S.CREATED_DATE) AS CREATED_DAY,
    MONTH(S.CREATED_DATE) AS CREATED_MONTH,
    YEAR(S.CREATED_DATE) AS CREATED_YEAR
FROM SOURCE_TABLE S
LEFT JOIN TARGET_TABLE T
ON S.ID = T.ID
WHERE T.ID IS NULL

SELECT * FROM TARGET_TABLE;



-- AFTER INSERTING DATA INTO THE TARGET TABLE , ADD SOME DATA INTO THE SOURCE TABLE

INSERT INTO SOURCE_TABLE VALUES
(3,'ALISH','2022-06-12');

--THEN NOT AUTOMATICALLY ADD INTO THE TARGET TABLE , WE HAVE MANUALLY RUN THE INSERT(TARGET_TABLE) SCRIPT 
-- THIS PROBLEM SOLVE BY THE TASK SCHEDULAR



-- CREATE SCHEDULE TASK FOR THE INSERTING DATA INTO THE TARGET TABLE
CREATE OR REPLACE TASK MY_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO TARGET_TABLE 
SELECT 
    S.ID,
    S.NAME,
    S.CREATED_DATE,
    DAY(S.CREATED_DATE) AS CREATED_DAY,
    MONTH(S.CREATED_DATE) AS CREATED_MONTH,
    YEAR(S.CREATED_DATE) AS CREATED_YEAR
FROM SOURCE_TABLE S
LEFT JOIN TARGET_TABLE T
ON S.ID = T.ID
WHERE T.ID IS NULL;

-- DISPLAY TARGET TABLE
SELECT * FROM TARGET_TABLE;



--SHOW ALL RUNNING TASK
SHOW TASKS;

--START THE TASK (RESUME)
ALTER TASK MY_TASK RESUME;

--STOP THE TASK (SUSPENED)
ALTER TASK MY_TASK SUSPEND;

//CHECK THE TASK STATUS
SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'MY_TASK'))