
/*
    =====CREATE TABLE WITH THE TIME TRAVEL=====

    1)AUTOMATIC WITH DEFAULT RETENTION PERIOD
        CREATE  TABLE MY_TABLE (C1 INTEGER);

    2)CUSTOMIZABLE RETENSION PERIOD
        CREATE TABLE MY_TABLE (C1 INTEGER)
        SET DATA_RETENSION_TIME_IN_DAYS = 90 

        ALTER TABLE MY_TABLE 
        SET  DATA_RETENSION_TIME_IN_DAYS = 30


    ===== QUERYING WITH THE TIME TRAVEL=====
    1. (AT, BEFORE)

    SELECT * FROM MY_TABLE1
    AT(TIMESTAMP => 'MON,01 MAY 2022 16:30:00 -0700::TIMESTAMP');

    SELECT * FROM MY_TABLE1
    BEFORE(STATEMENT => '***QUERY-ID***');

    2. (CLONE HISTORICAL DATA)

    CREATE TABLE RESTORED_TABLE CLONE MY_TABLE1
     AT(TIMESTAMP => 'MON,01 MAY 2022 16:30:00 -0700::TIMESTAMP')

    CREATE DATABASE RESTORED_DB CLONE MY_DB
     BEFORE(STATEMENT => '***QUERY-ID***');

    3. RESTORING OBJECTS 

    UNDROP TABLE/ SCHEMA / DATABASE
 
*/

CREATE OR REPLACE TABLE DROP_TABLE(
    ID INT,
    NAME VARCHAR
);

INSERT INTO DROP_TABLE VALUES 
(1,'JOHN'),
(2,'SAM'),
(3,'ELEN'),
(4,'MARK');

SELECT * FROM DROP_TABLE;

-- DELETE SOME RECORD(BY MISTAKE)
DELETE FROM DROP_TABLE WHERE ID = 4;

--RESTORE USING THE TIME (TRAVEL IN SOME BACK TIME)
SELECT * FROM DROP_TABLE AT(OFFSET => -60*5); --(BEFORE 5 MINUTE WHAT WAS THE DATA, THATS DATA FETCH)

-- SHOW ALL TABLE INFORMATION WHEN IT WAS CREATED
SHOW TABLES;

--SPECIFIC TIME
SELECT * FROM DROP_TABLE AT(TIMESTAMP => '2026-05-11 01:39:20.352 -0700'::TIMESTAMP_TZ);

--USING QUERY ID 
SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c44b07-000d-b44d-0000-00002f9dfc09');

--CREATE CLONE TABLE 
CREATE OR REPLACE TABLE DROP_TABLE_CLONE AS
SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c44b07-000d-b44d-0000-00002f9dfc09');

-- TRUNCATE ALL THE DATA AND INSERT NEW UPDATED DATA (TIME TRAVEL DATA)
TRUNCATE TABLE DROP_TABLE;

INSERT INTO DROP_TABLE 
SELECT * FROM DROP_TABLE_CLONE;

DROP TABLE DROP_TABLE_CLONE;

SELECT * FROM DROP_TABLE;



-- USING UNDROP KEYWORD --

DROP TABLE DROP_TABLE; 

SELECT * FROM DROP_TABLE;

-- REVERCE THE DROP TABLE 
UNDROP TABLE DROP_TABLE;

-- DROP AND UNDROP DATABASE AND SCHEMA 
-- THIS IS HAPPING USE OF THE MICRO PARTITIONING

DROP SCHEMA MYSCHEMA;
UNDROP SCHEMA MYSCHEMA;

DROP DATABASE MYDB;
UNDROP DATABASE MYDB;

SHOW DATABASES;
SHOW SCHEMAS;

ALTER TABLE DROP_TABLE 
SET DATA_RETENTION_TIME_IN_DAYS=30;

SHOW TABLES;