
/*
    =====CREATE TABLE WITH THE TIME TRAVEL=====

    1)AUTOMATIC WITH DEFAULT RETENTION PERIOD
        CREATE  TABLE MY_TABLE (C1 INTEGER);

    2)CUSTOMIZABLE RETENSION PERIOD
        CREATE TABLE MY_TABLE (C1 INTEGER)
        SET DATA_RETENSION_TIME_IN_DAYS = 90 

        ALTER TABLE MY_TABLE 
        SET  DATA_RETENSION_TIME_IN_DAYS = 30


    ===== QUERYING WITH THE TIME TRAVEL=====
    1. (AT, BEFORE)

    SELECT * FROM MY_TABLE1
    AT(TIMESTAMP => 'MON,01 MAY 2022 16:30:00 -0700::TIMESTAMP');

    SELECT * FROM MY_TABLE1
    BEFORE(STATEMENT => '***QUERY-ID***');

    2. (CLONE HISTORICAL DATA)

    CREATE TABLE RESTORED_TABLE CLONE MY_TABLE1
     AT(TIMESTAMP => 'MON,01 MAY 2022 16:30:00 -0700::TIMESTAMP')

    CREATE DATABASE RESTORED_DB CLONE MY_DB
     BEFORE(STATEMENT => '***QUERY-ID***');

    3. RESTORING OBJECTS 

    UNDROP TABLE/ SCHEMA / DATABASE

    4.

    
*/