
/*
    ======== ZERO COPY CLONING =======
    USE CASE : ASSUME THAT DO THE ONE CHANGES IN PRODUCTION DB. WHAT HAPPENING HERE, MAY HAPPENING DB CRASH, BUG ACCURING

    SO FOR THIS PROBLEM SOLVE BY THE ZERO COPY CLONING 
    LIKE CLONE THE PROD DB INTO THE TESTING DB AND PERFORM TESTING AND CHANGES

    IT IS NOT TAKE ANY OTHER SPACE AND POINT TO THE SAME MICRO PARTITIONING
    - IF DO THE CHANGES IN CLONE DB THEN IT IS GENERATE THE NEW MICRO PARTITIONING
              
*/

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;


----- ZERO COPY CLONING -----

-- CREATE TEST DB FROM THE ACTUAL DB
CREATE OR REPLACE DATABASE TEST_DB 
CLONE MYDB;

DROP DATABASE TEST_DB;